version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/httpstub
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.gradle" }}
          - v2-dependencies-

      - run:
          name: Build
          command: |
            ./gradlew build

      - store_test_results:
          path: build/test-results/test

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - deploy:
          name: Publish
          command: |
            if [ "$CIRCLE_TAG" ]; then
              curl -L -o ~/github-release.tar.bz2 https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
              tar -C ~ -jxf ~/github-release.tar.bz2
              export PATH=~/bin/linux/amd64:"$PATH"

              github-release release \
                --user int128 \
                --repo httpstub \
                --tag "$CIRCLE_TAG" \
                --name "$CIRCLE_TAG" \
                --description "Released on $(date +%Y-%m-%d)" || true

              github-release upload \
                --user int128 \
                --repo httpstub \
                --tag "$CIRCLE_TAG" \
                --name httpstub.jar \
                --file build/libs/httpstub.jar
            fi

deployment:
  publish:
    tag: /.*/
